# Generated by Django 3.1.6 on 2021-03-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
