# Generated by Django 3.1.6 on 2021-04-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0003_post_queries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
